// This file is like the "Main" part of the project that starts the web server.
using Microsoft.EntityFrameworkCore;
using QuantityMeasurementAPI.Middleware;
using QuantityMeasurementAppBusinessLayer.Interfaces;
using QuantityMeasurementAppBusinessLayer.Services;
using QuantityMeasurementAppRepoLayer.Data;
using QuantityMeasurementAppRepoLayer.Implementations;
using QuantityMeasurementAppRepoLayer.Interfaces;

// ── UC17: ASP.NET Core 8 Web API bootstrap ───────────────────────────────────
// Dependency graph (no circular references):
//   QuantityMeasurementAPI
//     → QuantityMeasurementBusinessLayer
//     → QuantityMeasurementRepoLayer   (owns ApplicationDbContext + EF Core)
//     → QuantityMeasurementModelLayer
// ─────────────────────────────────────────────────────────────────────────────

var builder = WebApplication.CreateBuilder(args);

// ── 1. Controllers + model validation ────────────────────────────────────────
builder.Services.AddControllers();

// ── 2. Swagger / OpenAPI ──────────────────────────────────────────────────────
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new Microsoft.OpenApi.Models.OpenApiInfo
    {
        Title       = "Quantity Measurement API",
        Version     = "v1",
        Description =
            "UC17 REST API for quantity measurement operations " +
            "(Compare, Convert, Add, Subtract, Divide) backed by EF Core + SQL Server. " +
            "Falls back to an in-memory cache repository when no connection string is configured."
    });

    // Wire up XML documentation generated by the .csproj GenerateDocumentationFile flag
    var xmlFile = $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    if (File.Exists(xmlPath))
        options.IncludeXmlComments(xmlPath);
});

// ── 3. EF Core DbContext + repository selection ───────────────────────────────
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");

if (!string.IsNullOrWhiteSpace(connectionString))
{
    // Register ApplicationDbContext (lives in RepoLayer) with SQL Server provider
    builder.Services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(
            connectionString,
            sqlOpts => sqlOpts.EnableRetryOnFailure(
                maxRetryCount:     3,
                maxRetryDelay:     TimeSpan.FromSeconds(5),
                errorNumbersToAdd: null)));

    Console.WriteLine("[Program] SQL Server connection string found — using EF Core repository.");

    builder.Services.AddScoped<IQuantityMeasurementRepository,
                               EFCoreQuantityMeasurementRepository>();
}
else
{
    Console.WriteLine("[Program] No connection string found — using in-memory Cache repository.");

    // Singleton so the same in-memory list is shared across scoped service requests
    builder.Services.AddSingleton<IQuantityMeasurementRepository>(
        _ => QuantityMeasurementCacheRepository.GetInstance());
}

// ── 4. Service layer ──────────────────────────────────────────────────────────
builder.Services.AddScoped<IQuantityMeasurementService, QuantityMeasurementServiceImpl>();

// ── 5. CORS ───────────────────────────────────────────────────────────────────
builder.Services.AddCors(options =>
    options.AddPolicy("AllowAll", policy =>
        policy.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader()));

// ── Build ─────────────────────────────────────────────────────────────────────
var app = builder.Build();

// ── 6. Auto-apply EF Core migrations on startup ───────────────────────────────
if (!string.IsNullOrWhiteSpace(connectionString))
{
    try
    {
        using var scope = app.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
        db.Database.Migrate();
        Console.WriteLine("[Program] EF Core migrations applied.");
    }
    catch (Exception ex)
    {
        Console.WriteLine("[Program] WARNING: migrations failed — " + ex.Message);
        Console.WriteLine("[Program] Ensure SQL Server is running and the database exists.");
    }
}

// ── 7. Swagger UI (Development only) ─────────────────────────────────────────
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "Quantity Measurement API v1");
        c.RoutePrefix = "swagger";
    });
}

// ── 8. Middleware pipeline ────────────────────────────────────────────────────
app.UseHttpsRedirection();
app.UseCors("AllowAll");
app.UseMiddleware<GlobalExceptionHandlingMiddleware>();
app.UseAuthorization();
app.MapControllers();

Console.WriteLine("[Program] Quantity Measurement API is running.");
Console.WriteLine("[Program] Swagger UI → http://localhost:5000/swagger");

app.Run();
